import type { Metadata } from "next";
import { Playwrite_US_Modern, Poppins } from "next/font/google";
import "./globals.css";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", '500', '600', "700"],
  variable: "--font-poppins",
});
const playwriteUsModern = Playwrite_US_Modern({
  weight: ["400"],
  variable: "--font-playwrite-us-modern",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${playwriteUsModern.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
